version: '3.8'
services:
  test-mongo:
    container_name: 'product-file-api'
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - TZ=Asia/Bangkok
    ports:
      - '7000:8080'
    volumes:
      - /file:/app/uploads

